name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PORT: ${{ secrets.PORT }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      STORAGE_URL: ${{ secrets.STORAGE_URL }}
      TEST_TEST: ${{ secrets.TEST_TEST }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > credentials.json
          mkdir -p /app/src/firebase/
          mv credentials.json /app/src/firebase/


      - name: Create .env file
        run: |
          echo "PORT=${PORT}" > .env
          echo "JWT_SECRET_KEY=${JWT_SECRET_KEY}" >> .env
          echo "STORAGE_URL=${STORAGE_URL}" >> .env
          echo "TEST_TEST=${TEST_TEST}" >> .env

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKERHUB_USERNAME/my-image:latest .
          echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
          docker push $DOCKERHUB_USERNAME/my-image:latest
